version: "3"
services:
  strapi:
    build: ./app
    ports:
      - 1337:1337
    volumes:
      - ./app:/usr/src/app
    environment:
      DATABASE_CLIENT: postgres
      DATABASE_HOST: db
      DATABASE_PORT: 5432
      DATABASE_NAME: strapi
      DATABASE_USERNAME: strapi
      DATABASE_PASSWORD: strapi
      DATABASE_SSL: "false"
    depends_on:
      - db
    command: sh -c "cd /usr/src/app && yarn install && yarn run develop"

  db:
    image: postgres:13
    environment:
      POSTGRES_USER: strapi
      POSTGRES_PASSWORD: strapi
      POSTGRES_DB: strapi
    volumes:
      - ./db-data:/var/lib/postgresql/data
